#!/usr/bin/env node

/**
 * EmailCommand
 */

var Email = require('../models/email');

var conditions = {
  sent: false,
  sendingCounter: {
    $lt: 5
  }
};

var i = 0;

var mailer = function () {
  console.log('zovem %d', ++i)
  Email.find(conditions).asc('priority').run(function (err, emails) {
    if (err) throw err;
    emails.forEach(function (email) {
      email.send(function (err) {
        if (err) throw err;
        console.log('poslat mail');
      });
    });
  });

  setTimeout(mailer, 100);
};

mailer();
