#!/usr/bin/env node

/**
 * EmailCommand
 */
 
var Email = require('../models/email'),
  cycleTime = 30000,
  conditions = {
    sent: false,
    sendingCounter: {
      $lt: 5
    }
  };

// TODO: error handling (now we just skip errors b/c that will stop command)
var mailer = function () {
  Email.find(conditions).asc('priority').run(function (err, emails) {
    // if (err) throw err;
    var len = emails.length;
    if (len) {
      emails.forEach(function (email) {
        email.doSend(function (err) {
          // if (err) throw err;
          if (--len === 0) { // next iteration
            setTimeout(mailer, cycleTime);
          }
        });
      });
    } else {
      setTimeout(mailer, cycleTime); //next iteration
    }
  });
};

// start command
mailer();