#!/usr/bin/env node

var Email = require('../models/email');

setInterval(function() {
    Email.find({}, function(err, emails) {
        emails.forEach(function(email) {
            email.send(function(err) {
                if (err) throw err;
            });
        });
    });
}, 10000);
