#!/usr/bin/env node

/**
 * EmailCommand
 */

var Email = require('../models/email');

var send = function() {
  var conditions = {
    sent: false,
    sendingCounter: {
      $lt: 5
    }
  };
  Email.find(conditions).asc('priority').run(function (err, emails) {
    emails.forEach(function (email) {
      console.log(email.message.to[0]);
      email.sendingCounter += 1;
      email.save();
      // email.send(function (err) {
      //   if (err) throw err;
      //     // email.save with status => sent...
      // });
    });
  });
  setInterval(send, 10000);
};

send();